_G.ViewBase = require "UI/ViewBase"
_G.AbstractCtrl = require "UI/AbstractCtrl"
_G.SubCtrlBase = require "UI/SubCtrlBase"
_G.CtrlBase = require "UI/CtrlBase"
_G.PanelItemBase = require "UI/PanelItemBase"
_G.PanelViewBase = require "UI/PanelViewBase"
